packages:
  - packages/*

catalog:
  "@biomejs/biome": ^1.9
  "@types/node": ^22
  lefthook: ^1.11
  np: ^10.2
  tsup: ^8.4
  typescript: ^5.8
  valibot: ^1.1.0
  vitest: ^3.1.3

onlyBuiltDependencies:
  - "@biomejs/biome"
  - lefthook
