packages:
  - packages/*

catalog:
  "@biomejs/biome": ^2.2
  "@types/node": ^24
  lefthook: ^1.12
  np: ^10.2
  tsdown: ^0.15
  typescript: ^5.8
  valibot: ^1.1.0
  vitest: ^3.2

onlyBuiltDependencies:
  - "@biomejs/biome"
  - lefthook
